name: bloc_and_dio_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_bloc: ^8.1.1
  http_interceptor: ^1.0.2
  dio: ^5.3.4
  http: ^0.13.1
  get: ^4.6.6
  lazy_load_scrollview: ^1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

linter:
  rules:
    - use_build_context_synchronously

flutter:
  uses-material-design: true
